name: Metrics
on:
  schedule: [{cron: "30 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: qe201020335
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Toronto
          
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_trim: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          
          plugin_lines: yes
          
          plugin_traffic: yes
          
          plugin_screenshot: yes
          plugin_screenshot_title: Some XKCD 
          plugin_screenshot_url: https://xkcd.com 
          plugin_screenshot_selector: "#comic img"
          plugin_screenshot_background: no  
